# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production: &production
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  eb_tier: <%= ENV["EB_TIER"] %>
  default_queue_url: <%= ENV["DEFAULT_QUEUE_URL"] %>
  default_url_host: <%= ENV["DEFAULT_URL_HOST"] %>
  aws_s3_access_key_id: <%= ENV["AWS_S3_ACCESS_KEY_ID"] %>
  aws_s3_secret_access_key: <%= ENV["AWS_S3_SECRET_ACCESS_KEY"] %>
  aws_region: <%= ENV["AWS_REGION"] %>
  uploads_bucket: <%= ENV["UPLOADS_BUCKET"] %>
  active_call_router_options: <%= ENV["ACTIVE_CALL_ROUTER_OPTIONS"] %>

development: &development
  <<: *production
  secret_key_base: df4c92af5777da2b6a84e84c8e259e0e432ef27096e57019c002dbdac8c050ef411065ae8f51ad15ce27c241093db3dc4885b35047d3d22023758a4d5da5e549
  eb_tier: "web"
  default_queue_url: "https://example.com/path/to/queue_name"
  default_url_host: "https://www.example.com"

test:
  <<: *development
  secret_key_base: e96898f527a2b4ca9246e053a8e5d6b1bd0e4911c5137f5ffbc0393cf42c8ee53bc3d0feb839b55b8ff21d187bba638c9e74e48ac14a3fe0589a3c081f067420
