br:
  operators:
    mundivox:
      prefixes: "*"
      metadata:
        gateway:
          host: "200.142.96.52"
kh:
  operators:
    smart:
      metadata:
        gateway:
          host: "27.109.112.140"
          prefix: false

    mobitel:
      metadata:
        gateway:
          host: "103.193.204.26"
          prefix: false

    metfone:
      metadata:
        gateway:
          host: "175.100.93.13"
          prefix: false

sl:
  operators:
    orange:
      metadata:
        gateway:
          host: "197.215.105.30"

so:
  operators:
    telesom:
      metadata:
        gateway:
          host: "41.78.73.242"

    golis:
      metadata:
        gateway:
          host: "41.78.73.242"

    nationlink:
      metadata:
        gateway:
          host: "41.78.73.242"

    somtel:
      metadata:
        gateway:
          host: "41.78.73.242"

    hormuud:
      metadata:
        gateway:
          host: "41.78.73.242"
