br:
  operators:
    mundivox:
      prefixes: "*"
      metadata:
        gateways:
          default:
            host: "200.142.96.52"
kh:
  operators:
    smart:
      metadata:
        gateways:
          default:
            host: "27.109.112.80"
            prefix: false
          "999999":
            host: "3.0.245.70"
    mobitel:
      metadata:
        gateways:
          default:
            host: "103.193.204.17"
            prefix: false
          "999999":
            host: "3.0.245.70"
    metfone:
      metadata:
        gateways:
          default:
            host: "175.100.32.29"
            prefix: false
          "999999":
            host: "3.0.245.70"
sl:
  operators:
    orange:
      metadata:
        gateways:
          default:
            host: "197.215.105.30"
so:
  operators:
    telesom:
      metadata:
        gateways:
          default:
            host: "41.78.73.242"
    golis:
      metadata:
        gateways:
          default:
            host: "41.78.73.242"
    nationlink:
      metadata:
        gateways:
          default:
            host: "41.78.73.242"
    somtel:
      metadata:
        gateways:
          default:
            host: "41.78.73.242"
    hormuud:
      metadata:
        gateways:
          default:
            host: "41.78.73.242"
